"""Stage 5: textbook draft (Dr. Yanagi clone).

Composes the style_engine guides + synthesis + fact-check into a system/context prompt
and produces the chapter draft with [!FIGURE] placeholders and a Vancouver reference list.
Output lands in content/drafts/<slug>_textbook.md so app/editor can open it.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

from . import paths, prompts
from .adapters.llm import LLMAdapter, get_llm
from .brief import Brief
from .references import Reference


def _reference_block(refs: list[Reference]) -> str:
    lines = ["## 参考文献", ""]
    for i, r in enumerate(refs, 1):
        lines.append(f"{i}. {r.vancouver()}")
    return "\n".join(lines)


def _outline_text(brief: Brief) -> str:
    if not brief.outline:
        return "(outline 指定なし。テーマに即した教科書的構成を設計せよ)"
    return "\n".join(f"{i}. {h}" for i, h in enumerate(brief.outline, 1))


def build_draft(
    brief: Brief,
    synthesis_path: Path,
    factcheck_path: Path,
    refs: list[Reference],
    out_dir: Path,
    llm: LLMAdapter | None = None,
) -> Path:
    llm = llm or get_llm()
    synthesis_md = synthesis_path.read_text(encoding="utf-8")
    factcheck_md = factcheck_path.read_text(encoding="utf-8") if factcheck_path.exists() else ""

    ref_list_preview = "\n".join(f"[{i}] {r.title} ({r.year})" for i, r in enumerate(refs, 1))

    task = (
        f"章タイトル: {brief.title}\n\n"
        f"想定構成（outline）:\n{_outline_text(brief)}\n\n"
        "CONTEXT には (1) スタイルガイド類, (2) 知見サマリー, (3) ファクトチェック結果, "
        "(4) 参考文献リスト(番号付き) が含まれる。これらに忠実に、教科書本文を執筆せよ。\n"
        "本文中の医学的主張には参考文献番号 [n] を付し、章末に「## 参考文献」を Vancouver 形式で必ず置く"
        "（番号は下記の参考文献リストに一致させる）。\n"
        "図表が要る箇所には [!FIGURE] プレースホルダを置く。\n\n"
        f"## 参考文献リスト（[n] の対応）\n{ref_list_preview}"
    )

    context = prompts.draft_style_context() + [
        "## 知見サマリー\n" + synthesis_md,
        "## ファクトチェック結果\n" + factcheck_md,
    ]

    result = llm.generate(
        system=prompts.DRAFT_SYSTEM,
        prompt=task,
        context_docs=context,
        prompt_dump=out_dir / "draft.prompt.txt",
    )

    body = result.text
    # Guarantee a reference section exists even in dry mode (so the editor can link it).
    if "## 参考文献" not in body:
        body = body.rstrip() + "\n\n" + _reference_block(refs) + "\n"

    today = date.today().strftime("%Y%m%d")
    out_name = f"{today}_{brief.slug}_textbook.md"
    out_path = paths.DRAFTS_DIR / out_name
    front = (
        f"<!-- generated by Textbook Studio pipeline | provider: {result.provider}"
        f"{' (dry/手動: draft.prompt.txt を NotebookLM/Google Pro に貼って生成)' if result.dry else ''} -->\n\n"
    )
    out_path.write_text(front + body, encoding="utf-8")

    # Keep a copy in the stage out dir too.
    (out_dir / "draft.md").write_text(front + body, encoding="utf-8")
    print(f"[draft] -> {out_path}" + (" (dry mode)" if result.dry else ""))
    return out_path
